
// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  // tutorialSidebar: [{type: 'autogenerated', dirName: '.'}],

  // But we can create a sidebar manually
  tutorialSidebar: [
    'introduction',
    {
      type: 'category',
      label: 'The MIKO Protocol',
      items: [
        'miko-protocol/core-components',
        'miko-protocol/symbiotic-loop-and-economics',
      ],
    },
    {
        type: 'category',
        label: 'Technical Architecture',
        items: [
            'technical-architecture/ai-architecture',
            'technical-architecture/smart-contracts',
        ],
    },
    {
        type: 'category',
        label: 'Ecosystem & Vision',
        items: [
            'ecosystem/competitive-landscape',
            'ecosystem/tokenomics-and-distribution',
            'ecosystem/roadmap',
        ],
    },
    {
        type: 'category',
        label: 'Security & Risks',
        items: [
            'security/risks-and-transparency',
        ],
    },
    'conclusion',
  ],
};

export default sidebars;
